package geo

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/ht4w5/bd2geo/internal/model"
)

type GeneratorConfig struct {
	// Name of created variable.
	// E.g. "$geo".
	// Must not be empty.
	VariableName string
	// Name of address variable used
	// by the geo block.
	// E.g. "$arg_remote_addr".
	// Can be empty (Nginx uses "$remote_addr").
	AddressVariableName string
	// Default value when unmatched.
	// Can be empty.
	DefaultString string
}

// Generator generates an Nginx geo block.
type Generator struct {
	cfg GeneratorConfig
}

func NewGenerator(cfg GeneratorConfig) (*Generator, error) {
	if cfg.VariableName == "" {
		return nil, errors.New("VariableName must not be empty")
	}
	gg := &Generator{
		cfg: cfg,
	}
	return gg, nil
}

func (g *Generator) Generate(w io.Writer, now func() time.Time, report *model.Report, hash uint32) error {
	if report == nil {
		return errors.New("nil report")
	}
	if w == nil {
		return errors.New("nil writer")
	}
	if now == nil {
		now = time.Now
	}

	bw := bufio.NewWriter(w)

	var writeErr error
	writeString := func(s string) bool {
		if writeErr != nil {
			return false
		}
		_, writeErr = bw.WriteString(s)
		return writeErr == nil
	}

	if !writeString("# Generated by bd2geo. DO NOT EDIT.\n") ||
		!writeString(fmt.Sprintf("# Time of generation: %s\n", now().Format(time.RFC3339))) ||
		!writeString(fmt.Sprintf("# Report hash: %x\n", hash)) ||
		!writeString(fmt.Sprintf(
			"geo %s %s {\n",
			g.cfg.AddressVariableName,
			g.cfg.VariableName,
		)) {
		return writeErr
	}

	for _, f := range report.Findings {
		if !writeString(fmt.Sprintf(
			"    %s %q;\n",
			f.Target.String(),
			f.ReasonsStr(),
		)) {
			return writeErr
		}
	}

	if !writeString("}\n") {
		return writeErr
	}

	if err := bw.Flush(); err != nil {
		return fmt.Errorf("flush geo block: %w", err)
	}

	return nil
}
