package geo

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"time"

	"github.com/ht4w5/bandaid/internal/info"
	"github.com/ht4w5/bandaid/internal/model"
)

type GeneratorConfig struct {
	// Name of created variable.
	// E.g. "$geo".
	// Must not be empty.
	VariableName string
	// Name of address variable used
	// by the geo block.
	// E.g. "$arg_remote_addr".
	// Can be empty (Nginx uses "$remote_addr").
	AddressVariableName string
	// Default value when unmatched.
	// Can be empty.
	DefaultString string
}

// Generator generates an Nginx geo block.
type Generator struct {
	cfg GeneratorConfig
}

func NewGenerator(cfg GeneratorConfig) (*Generator, error) {
	if cfg.VariableName == "" {
		return nil, errors.New("VariableName must not be empty")
	}
	gg := &Generator{
		cfg: cfg,
	}
	return gg, nil
}

// Generate writes report as an Nginx geo block to w.
//
// now must not be nil; it supplies the generation timestamp in the block
// header. Write failures are reported only by the final flush: bufio.Writer
// remembers a failed flush and the flush returns it, wrapped as
// "flush geo block: ...".
func (g *Generator) Generate(w io.Writer, now func() time.Time, report *model.Report, hash uint32) error {
	if report == nil {
		return errors.New("nil report")
	}
	if w == nil {
		return errors.New("nil writer")
	}

	bw := bufio.NewWriter(w)

	fmt.Fprintf(bw, "# Generated by %s. DO NOT EDIT.\n", info.Header())
	fmt.Fprintf(bw, "# Time of generation: %s\n", now().Format(time.RFC3339))
	fmt.Fprintf(bw, "# Report hash: %x\n", hash)

	if g.cfg.AddressVariableName == "" {
		fmt.Fprintf(bw, "geo %s {\n", g.cfg.VariableName)
	} else {
		fmt.Fprintf(bw, "geo %s %s {\n", g.cfg.AddressVariableName, g.cfg.VariableName)
	}

	if g.cfg.DefaultString != "" {
		fmt.Fprintf(bw, "    default %q;\n", g.cfg.DefaultString)
	}

	for _, f := range report.Findings {
		fmt.Fprintf(bw, "    %s %q;\n", f.Target.String(), f.ReasonsStr())
	}

	fmt.Fprint(bw, "}\n")

	if err := bw.Flush(); err != nil {
		return fmt.Errorf("flush geo block: %w", err)
	}

	return nil
}
