package geo_test

import (
	"bytes"
	"errors"
	"net/netip"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/ht4w5/bandaid/internal/geo"
	"github.com/ht4w5/bandaid/internal/model"
)

// fixedNow is the deterministic clock injected into Generator.Generate:
// 2026-01-02T03:04:05Z (RFC 3339: "2026-01-02T03:04:05Z").
func fixedNow() time.Time {
	return time.Date(2026, time.January, 2, 3, 4, 5, 0, time.UTC)
}

func mustGenerator(t *testing.T, cfg geo.GeneratorConfig) *geo.Generator {
	t.Helper()
	g, err := geo.NewGenerator(cfg)
	if err != nil {
		t.Fatalf("NewGenerator(%+v): unexpected error: %v", cfg, err)
	}
	if g == nil {
		t.Fatalf("NewGenerator(%+v): got nil generator with nil error", cfg)
	}
	return g
}

// generatedHeaderRe pins the structure of the "# Generated by" line: the
// generator's build identity (name, version, optionally a commit) framed by
// the fixed text. The identity is injected via ldflags at build time, so it is
// checked structurally here instead of being recomputed from internal/info.
var generatedHeaderRe = regexp.MustCompile(`\A# Generated by bandaid \S+( \S+)?\. DO NOT EDIT\.\n`)

// withoutHeader validates the generated-by line and returns the rest of the
// output, whose parts are all fixed and asserted against hand-written literals.
func withoutHeader(t *testing.T, out string) string {
	t.Helper()
	loc := generatedHeaderRe.FindStringIndex(out)
	if loc == nil {
		first := out
		if i := strings.IndexByte(out, '\n'); i >= 0 {
			first = out[:i]
		}
		t.Fatalf("generated-by line does not match %v; got %q", generatedHeaderRe, first)
	}
	return out[loc[1]:]
}

func TestNewGeneratorRejectsEmptyVariableName(t *testing.T) {
	g, err := geo.NewGenerator(geo.GeneratorConfig{})
	if err == nil {
		t.Fatal("NewGenerator with empty VariableName: got nil error, want rejection")
	}
	if g != nil {
		t.Errorf("NewGenerator with empty VariableName: got generator %+v, want nil", g)
	}
	if !strings.Contains(err.Error(), "VariableName") {
		t.Errorf("error %q should name the offending field", err)
	}
}

func TestNewGeneratorAcceptsMinimalConfig(t *testing.T) {
	// Only VariableName is required; address variable and default may be empty.
	mustGenerator(t, geo.GeneratorConfig{VariableName: "$geo"})
}

func TestGenerateRejectsNilReport(t *testing.T) {
	g := mustGenerator(t, geo.GeneratorConfig{VariableName: "$geo"})

	err := g.Generate(&bytes.Buffer{}, fixedNow, nil, 0)
	if err == nil {
		t.Fatal("Generate with nil report: got nil error, want rejection")
	}
	if !strings.Contains(err.Error(), "nil report") {
		t.Errorf("error %q should say the report is nil", err)
	}
}

func TestGenerateRejectsNilWriter(t *testing.T) {
	g := mustGenerator(t, geo.GeneratorConfig{VariableName: "$geo"})

	err := g.Generate(nil, fixedNow, &model.Report{}, 0)
	if err == nil {
		t.Fatal("Generate with nil writer: got nil error, want rejection")
	}
	if !strings.Contains(err.Error(), "nil writer") {
		t.Errorf("error %q should say the writer is nil", err)
	}
}

func TestGenerateRendersGoldenGeoBlock(t *testing.T) {
	report := &model.Report{Findings: []model.Finding{
		{Target: netip.MustParsePrefix("10.0.0.0/8"), Reasons: []string{"alpha", "beta"}},
		{Target: netip.MustParsePrefix("192.0.2.0/24"), Reasons: []string{"probe"}},
		{Target: netip.MustParsePrefix("2001:db8::/32"), Reasons: []string{"v6", "scan"}},
	}}
	g := mustGenerator(t, geo.GeneratorConfig{
		VariableName:        "$geo",
		AddressVariableName: "$arg_remote_addr",
		DefaultString:       "none",
	})

	var buf bytes.Buffer
	if err := g.Generate(&buf, fixedNow, report, 0xdeadbeef); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	// Expected block written by hand from the nginx geo syntax:
	//
	//   geo [$address] $variable {
	//       default <value>;
	//       <network> <value>;
	//       ...
	//   }
	//
	// Entry values are the finding value contract (reasons joined with ":")
	// rendered with Go %q quoting. Hash 0xdeadbeef renders as hex "deadbeef".
	const want = `# Time of generation: 2026-01-02T03:04:05Z
# Report hash: deadbeef
geo $arg_remote_addr $geo {
    default "none";
    10.0.0.0/8 "alpha:beta";
    192.0.2.0/24 "probe";
    2001:db8::/32 "v6:scan";
}
`

	got := withoutHeader(t, buf.String())
	if got != want {
		t.Errorf("geo block mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateHeaderIdentifiesGenerator(t *testing.T) {
	g := mustGenerator(t, geo.GeneratorConfig{VariableName: "$geo"})

	var buf bytes.Buffer
	if err := g.Generate(&buf, fixedNow, &model.Report{}, 0); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	end := strings.IndexByte(buf.String(), '\n') + 1
	if end == 0 {
		t.Fatalf("output has no header line: %q", buf.String())
	}
	first := buf.String()[:end]
	if !generatedHeaderRe.MatchString(first) {
		t.Errorf("generated-by line %q does not match %v", strings.TrimSuffix(first, "\n"), generatedHeaderRe)
	}
}

func TestGenerateWritesDefaultStringWhenSet(t *testing.T) {
	// Regression bd6550e: the default line was not written at all.
	report := &model.Report{Findings: []model.Finding{
		{Target: netip.MustParsePrefix("10.0.0.0/8"), Reasons: []string{"alpha"}},
	}}
	g := mustGenerator(t, geo.GeneratorConfig{VariableName: "$geo", DefaultString: "none"})

	var buf bytes.Buffer
	if err := g.Generate(&buf, fixedNow, report, 0); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	const want = `# Time of generation: 2026-01-02T03:04:05Z
# Report hash: 0
geo $geo {
    default "none";
    10.0.0.0/8 "alpha";
}
`

	got := withoutHeader(t, buf.String())
	if got != want {
		t.Errorf("geo block mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateOmitsDefaultWhenEmpty(t *testing.T) {
	report := &model.Report{Findings: []model.Finding{
		{Target: netip.MustParsePrefix("10.0.0.0/8"), Reasons: []string{"alpha"}},
	}}
	g := mustGenerator(t, geo.GeneratorConfig{
		VariableName:        "$geo",
		AddressVariableName: "$arg_remote_addr",
	})

	var buf bytes.Buffer
	if err := g.Generate(&buf, fixedNow, report, 0); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	const want = `# Time of generation: 2026-01-02T03:04:05Z
# Report hash: 0
geo $arg_remote_addr $geo {
    10.0.0.0/8 "alpha";
}
`

	got := withoutHeader(t, buf.String())
	if got != want {
		t.Errorf("geo block mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateRendersAddressVariableNameWhenSet(t *testing.T) {
	g := mustGenerator(t, geo.GeneratorConfig{
		VariableName:        "$geo",
		AddressVariableName: "$arg_remote_addr",
	})

	var buf bytes.Buffer
	if err := g.Generate(&buf, fixedNow, &model.Report{}, 0); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	const want = `# Time of generation: 2026-01-02T03:04:05Z
# Report hash: 0
geo $arg_remote_addr $geo {
}
`

	got := withoutHeader(t, buf.String())
	if got != want {
		t.Errorf("geo block mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

func TestGenerateOmitsAddressVariableWhenEmpty(t *testing.T) {
	// With no address variable nginx uses "$remote_addr" implicitly:
	// the opening must be plain "geo $geo {".
	g := mustGenerator(t, geo.GeneratorConfig{
		VariableName:  "$geo",
		DefaultString: "none",
	})

	var buf bytes.Buffer
	if err := g.Generate(&buf, fixedNow, &model.Report{}, 0); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	const want = `# Time of generation: 2026-01-02T03:04:05Z
# Report hash: 0
geo $geo {
    default "none";
}
`

	got := withoutHeader(t, buf.String())
	if got != want {
		t.Errorf("geo block mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}

var errBoom = errors.New("boom")

// failAfterWriter accepts up to limit bytes, then fails every further write
// with a short write and err, like a broken pipe or full disk would.
type failAfterWriter struct {
	limit int
	n     int
	err   error
}

func (w *failAfterWriter) Write(p []byte) (int, error) {
	if w.n+len(p) <= w.limit {
		w.n += len(p)
		return len(p), nil
	}
	short := w.limit - w.n
	if short < 0 {
		short = 0
	}
	w.n = w.limit
	return short, w.err
}

func TestGenerateReturnsWriterError(t *testing.T) {
	small := &model.Report{Findings: []model.Finding{
		{Target: netip.MustParsePrefix("10.0.0.0/8"), Reasons: []string{"alpha"}},
	}}
	// big renders well past the 4 KiB bufio buffer, so writes to the
	// underlying writer fail mid-stream instead of only at flush time.
	big := &model.Report{Findings: make([]model.Finding, 500)}
	for i := range big.Findings {
		big.Findings[i] = model.Finding{
			Target:  netip.MustParsePrefix("10.0.0.0/8"),
			Reasons: []string{"alpha-reason", "beta-reason"},
		}
	}

	g := mustGenerator(t, geo.GeneratorConfig{VariableName: "$geo"})

	cases := []struct {
		name   string
		limit  int
		report *model.Report
	}{
		{name: "writer fails immediately", limit: 0, report: small},
		{name: "writer fails mid-stream", limit: 500, report: big},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			w := &failAfterWriter{limit: tc.limit, err: errBoom}
			err := g.Generate(w, fixedNow, tc.report, 0)
			if err == nil {
				t.Fatal("Generate: got nil error, want writer failure surfaced")
			}
			if !errors.Is(err, errBoom) {
				t.Errorf("Generate error %q should wrap the writer error %q", err, errBoom)
			}
		})
	}
}

func TestGenerateRendersEmptyReportAsEmptyBlock(t *testing.T) {
	g := mustGenerator(t, geo.GeneratorConfig{
		VariableName:        "$geo",
		AddressVariableName: "$arg_remote_addr",
		DefaultString:       "none",
	})

	var buf bytes.Buffer
	if err := g.Generate(&buf, fixedNow, &model.Report{}, 0); err != nil {
		t.Fatalf("Generate: %v", err)
	}

	// An empty report must still yield a syntactically valid nginx geo block:
	// opening line and closing brace with no entry lines in between, even with
	// every optional setting configured.
	const want = `# Time of generation: 2026-01-02T03:04:05Z
# Report hash: 0
geo $arg_remote_addr $geo {
    default "none";
}
`

	got := withoutHeader(t, buf.String())
	if got != want {
		t.Errorf("geo block mismatch\ngot:\n%s\nwant:\n%s", got, want)
	}
}
